"""Generate and execute the round-2 walkthrough notebook.

The notebook is the submission's "NLP Model Script/Notebook" deliverable. It is
written here rather than by hand so that it cannot drift from the modules it
calls, and it is executed before it is saved, so every output a judge sees was
produced by the code above it.

    python build_notebook.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import nbformat as nbf
from nbclient import NotebookClient

from config import ROUND2

OUT = ROUND2 / "notebooks" / "Round2_NLP_Team_SE7EN.ipynb"

MD = nbf.v4.new_markdown_cell
CODE = nbf.v4.new_code_cell


def cells() -> list:
    return [
        MD("""# Rebuilding the Social Engine — Round 2

**Team SE7EN** · Tanmay Singh · Panshul Arora
Data Vortex A'26 · Round 2 · NLP comprehension layer

---

This notebook walks the whole pipeline end to end on Dataset 2: audit the labels,
preprocess, build features, select a model, evaluate honestly, analyse the errors.

Every cell below has been executed; the outputs are what the code produced.
The same steps run headless with `python round2/run_round2.py`.

**Contents**

1. Load and profile the corpus
2. Two data-quality findings that changed the design
3. Preprocessing
4. Features
5. Model selection under grouped cross-validation
6. Held-out evaluation
7. Error analysis
8. Inference"""),

        CODE("""import sys, warnings, json
from pathlib import Path
warnings.filterwarnings("ignore")

SRC = Path.cwd().parent / "src" if Path.cwd().name == "notebooks" else Path("round2/src")
sys.path.insert(0, str(SRC.resolve()))

import numpy as np, pandas as pd
import sklearn
print("python     ", sys.version.split()[0])
print("scikit-learn", sklearn.__version__)
print("pandas     ", pd.__version__)"""),

        MD("## 1. Load and profile the corpus"),

        CODE("""from dataio import load, sha256, duplicate_report

df = load()
print("rows:", len(df), " sha256:", sha256()[:24], "...")
df.head(4)[["text_id", "post_text", "sentiment_label", "topic_category"]]"""),

        CODE("""print("sentiment_label")
print(df.sentiment_label.value_counts().to_string())
print()
print("topic_category")
print(df.topic_category.value_counts().to_string())
print()
words = df.post_text.str.split().str.len()
print(f"post length: median {words.median():.0f} words, "
      f"range {words.min()}-{words.max()}; no nulls anywhere: {df.isna().sum().sum() == 0}")"""),

        MD("""Sentiment is exactly balanced at 3,000 per class. Topic is not: 86% of the
corpus is `Community_Discussion` and `Account_Security` has 136 posts. That 57:1 skew
is why **macro-F1** leads every table in this submission — a model that only ever says
`Community_Discussion` would score 0.861 accuracy and be useless."""),

        MD("""## 2. Two data-quality findings that changed the design

### 2.1 — 1,100 rows are duplicate posts"""),

        CODE("""dup = duplicate_report(df)
for k, v in dup.items():
    print(f"{k:32s} {v}")"""),

        MD("""Every repeat carries an identical label, so the duplicates are not annotation
noise — they are the same post counted twice. Harmless for training, **dangerous for
evaluation**: a random row split puts copies of one post on both sides and grades the
model on memorised strings.

So we split on the *unique post*, never on the row — and we measure what the shortcut
would have been worth (Section 5)."""),

        MD("""### 2.2 — `topic_category` is generated by a substring rule

A character-ngram model beat a word-ngram model on `topic_category` by 23 macro-F1
points. Topics live in words, so that ordering is backwards. The top character
features said why: `ban`, `app`, `ui`, `mode` — substrings, not words.

`audit_labels.py` mines the rule from scratch and replays it."""),

        CODE("""from audit_labels import RECOVERED_RULE, PRIORITY, DEFAULT_CLASS, apply_rule

predicted = apply_rule(df.post_text)
fidelity = (predicted == df.topic_category).mean()
print(f"fidelity: {fidelity:.4f}  ({(predicted == df.topic_category).sum()} / {len(df)} rows)")
print()
for cls in PRIORITY:
    print(f"  {cls:22s} <- any of {RECOVERED_RULE[cls]}")
print(f"  {DEFAULT_CLASS:22s} <- (everything else)")"""),

        MD("""**9,000 of 9,000 rows, exactly.** `topic_category` is not an annotation; it is a
case-insensitive substring switch over the raw post.

Because it matches substrings rather than words, the damage is easy to see:"""),

        CODE("""probe = [
    "That Janet Jackson. Sometimes she just gets me. Happy Friday friends!",
    "Kenneth Downing Jr., guitarist in the British heavy metal band JUDAS PRIEST",
    "I use to love that song in the 8th grade. Trina was my role model lmfao",
    "Jurassic Park is screening at the Actors Playhouse this weekend for free",
]
for text in probe:
    print(f"{apply_rule(pd.Series([text]))[0]:22s} <- {text[:68]}")"""),

        MD("""Three consequences, and they shape everything after this cell:

1. The **Bayes error of the topic task is exactly zero** — the label is a deterministic
   function of the input. A perfect score is attainable and meaningless.
2. A topic model is rewarded for **recovering substrings**, not topics.
3. Roughly **one post in eight** carries a topic a human would call wrong.

We report this rather than harvesting the free 1.000. Sentiment shows no such
structure — cue words are graded ("love" is 81% Positive, not 100%), which is what
human annotation looks like."""),

        CODE("""for kw in ["love", "hate", "happy", "worst", ":)", ":("]:
    hit = df.post_text.str.lower().str.contains(kw, regex=False)
    share = df.sentiment_label[hit].value_counts(normalize=True).round(2).to_dict()
    print(f"{kw:8s} n={hit.sum():4d}  {share}")"""),

        MD("""## 3. Preprocessing

The corpus carries damage from a bad serialisation round-trip (`\\u002c` escapes, leaked
CSV quoting) on top of ordinary social noise. Normalisation repairs that and
canonicalises what is noise for a bag-of-ngrams model, while **preserving** what an
annotator actually used — emoticons, punctuation runs, hashtag bodies.

Negation scope is marked so that *"not a good day"* stops sharing every unigram with
*"a good day"*."""),

        CODE("""from preprocess import normalise, prepare

demo = [
    "I'm sooooo happy :) #GoodFriday @user http://t.co/x",
    "not a good day at all!!!",
    'Dwight Howard gets his 4th career 30-point\\\\u002c 10-rebound game.\\\\" Too bad it comes in a loss',
]
for text in demo:
    print("raw :", text)
    print("prep:", prepare(text))
    print()"""),

        MD("""What we deliberately **did not** do: no stop-word removal (`not`, `no`, `but` are all
on standard stop lists and all three are polarity-bearing), no stemming (it destroys
the substring evidence the topic task runs on), no external sentiment lexicon."""),

        MD("""## 4. Features

Three complementary views, concatenated into one sparse matrix:

| block | what | why |
|---|---|---|
| `word` | TF-IDF 1–2 grams over the normalised text | lexical polarity, topical content |
| `char` | TF-IDF character n-grams inside word boundaries | misspellings, elongation, hashtag compounds — and substrings |
| `surface` | 11 counts from the **raw** string | the cues normalisation is about to destroy |"""),

        CODE("""from features import build_features, SurfaceStats, STAT_NAMES

union = build_features()
X = union.fit_transform(df.post_text[:2000])
print("feature matrix:", X.shape, f"({X.nnz / X.shape[0]:.0f} non-zeros per post)")
print()
print("surface block:")
print(pd.DataFrame(SurfaceStats().transform(df.post_text[:3].tolist()),
                   columns=STAT_NAMES).round(2).to_string(index=False))"""),

        MD("""## 5. Model selection under grouped cross-validation

Eight candidates per task, scored with 5-fold `StratifiedGroupKFold` — stratified on
the label, grouped on the post, so no fold is ever graded on text it trained on.
Vectorisers are fitted **inside** each fold.

The list is an ablation: feature blocks are added one at a time with the classifier
held fixed, then the model family is varied with the features held fixed."""),

        CODE("""from config import REPORTS

for task in ["sentiment", "topic"]:
    t = pd.read_csv(REPORTS / f"model_comparison_{task}.csv")
    print(f"=== {task} " + "=" * 52)
    print(t[["model", "cv_f1_macro", "cv_f1_macro_std", "cv_accuracy"]]
          .round(4).to_string(index=False))
    print()"""),

        MD("""Read the two tables side by side and they disagree about features, which is the
point:

- **Sentiment**: word → char → word+char → word+char+surface climbs monotonically.
  The views are complementary, so we pay for all three.
- **Topic**: the character block *alone* wins, and adding the word block **costs**
  10 macro-F1 points. A word tokeniser cannot see `app` inside `happy`. This is
  Section 2.2 resurfacing as a model-selection result.

The winning character range for topic is **2–3** — the length of `ui`, `ban`, `app`,
`bug`. The hyperparameter that wins tells you what the label is made of."""),

        MD("### How much would a duplicate-blind split have invented?"),

        CODE("""import joblib
from config import MODEL_BUNDLE

bundle = joblib.load(MODEL_BUNDLE)
for task, leak in bundle["leakage"].items():
    print(f"{task:10s} grouped {leak['grouped_by_text_f1_macro']:.4f}  |  "
          f"random-row {leak['random_row_split_f1_macro']:.4f}  |  "
          f"inflation +{leak['inflation']:.4f}")"""),

        MD("""## 6. Held-out evaluation

20% of unique posts, stratified, untouched by every step above and scored exactly
once."""),

        CODE("""from sklearn.metrics import classification_report
from dataio import make_split
from config import TASKS

for task, col in TASKS.items():
    split = make_split(df, task)
    model = bundle["models"][task]
    y_true = split.test[col].to_numpy()
    y_pred = model.predict(split.test.post_text.to_numpy())
    print(f"=== {task}  ({bundle['selected'][task]})")
    print(classification_report(y_true, y_pred, zero_division=0))"""),

        CODE("""metrics = json.loads((REPORTS / "metrics.json").read_text(encoding="utf-8"))
rows = []
for task in TASKS:
    b = metrics["tasks"][task]
    rows.append({"task": task, "macro_F1": b["macro_f1"], "accuracy": b["accuracy"],
                 "weighted_F1": b["weighted_f1"], "kappa": b["cohen_kappa"],
                 "MCC": b["matthews_corrcoef"]})
pd.DataFrame(rows).round(4)"""),

        MD("""## 7. Error analysis

### Sentiment — are the mistakes confident?"""),

        CODE("""b = metrics["tasks"]["sentiment"]["error_profile"]
print(f"mean confidence when right : {b['mean_conf_correct']:.3f}")
print(f"mean confidence when wrong : {b['mean_conf_wrong']:.3f}")
print(f"errors made above 0.8 conf : {b['share_of_errors_above_0_8_conf']:.1%}")
print()
err = pd.read_csv(REPORTS / "errors_sentiment.csv")
print("highest-confidence mistakes:")
for _, r in err.head(5).iterrows():
    print(f"  [{r.actual} -> {r.predicted}, p={r.confidence:.2f}] {str(r.post_text)[:84]}")"""),

        MD("""The separation between the two confidences is what makes a confidence threshold a
usable routing control: the engine can hand its hard cases to a human instead of
guessing.

The named failure modes — idiomatic negation (`can't wait`), context-dependent
polarity (sports and politics), the Neutral boundary on reporting-voice posts, and
sarcasm — are worked through in the technical report.

### Topic — the errors are rare-trigger recovery failures"""),

        CODE("""rd = metrics["tasks"]["topic"]["rule_diagnosis"]
print(f"error rate, no trigger present     : {rd['error_rate_no_trigger']:.1%}")
print(f"error rate, trigger in >= 60 posts : {rd['error_rate_common_trigger']:.1%}")
print(f"error rate, trigger in <  60 posts : {rd['error_rate_rare_trigger']:.1%}")
print()
print(f"learned model held-out accuracy    : {rd['model_accuracy']:.4f}")
print(f"recovered rule held-out accuracy   : {rd['rule_accuracy']:.4f}")"""),

        MD("""The whole gap is rare-trigger recovery. The topic task has no modelling problem
left to solve — it has a **labelling** problem. More data or a bigger model would
converge on the same rule and would all be learning an artefact.

**Recommendation:** re-annotate `topic_category` before deploying it for routing. The
pipeline here transfers unchanged, because nothing in it was tuned to the rule."""),

        MD("## 8. Inference"),

        CODE("""from predict import score

score([
    "the app keeps crashing right after the latest update, fix this please",
    "absolutely loved the new dark mode, best thing you've shipped all year",
    "Parliament meets on Thursday to discuss the budget",
    "someone tried to log into my account from another country",
])"""),

        MD("""---

### Deliverables produced by this pipeline

| Deliverable | File |
|---|---|
| NLP model notebook | this file |
| Trained models | `round2/models/social_engine_nlp_team_se7en.pkl` |
| Evaluation metrics report | `round2/reports/Evaluation_Metrics_Report_Team_SE7EN.pdf` |
| Technical report | `round2/reports/Round2_Technical_Report_Team_SE7EN.pdf` |

Rebuild everything from the raw CSV with `python round2/run_round2.py`.

**Team SE7EN** — Tanmay Singh · Panshul Arora"""),
    ]


def main():
    nb = nbf.v4.new_notebook(cells=cells())
    nb.metadata.update({
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": sys.version.split()[0]},
    })
    OUT.parent.mkdir(parents=True, exist_ok=True)
    print(f"executing {len(nb.cells)} cells ...", flush=True)
    NotebookClient(nb, timeout=900, kernel_name="python3",
                   resources={"metadata": {"path": str(OUT.parent)}}).execute()
    nbf.write(nb, OUT)
    print(f"wrote {OUT.relative_to(ROUND2.parent)} "
          f"({OUT.stat().st_size / 1e6:.2f} MB)")
    return OUT


if __name__ == "__main__":
    main()
